version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Sistema-Votacao"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-eoij7l6b464u"
s3_prefix = "Sistema-Votacao"
region = "sa-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
